---
- name: paquetes basicos
  hosts: all
  tasks:
    - name: apt-get update
      package:
        update_cache: true
    - name: some basic packages
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - python3-apt
        - vim
        - openssh-server
        - nfs-common
          #        - ntp
        - sudo
        - htop
        - duf
    - name: copy vimrc to home
      ansible.builtin.copy:
        src: files/vimrc
        dest: /home/emeteo/.vimrc
        owner: emeteo
        group: emeteo
        mode: 0644
- name: paquetes en laptops et vm
  hosts: laptops vm
  tasks:
    - name: git
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - git
- name: paquetes para VM (Proxmox)
  hosts: vm
  tasks:
    - name: qemu-guest-agent
      package:
        name: qemu-guest-agent
        state: latest
    - name: make sure qemu-guest-agent is started
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
    - name: install watchdog
      package: 
        name: watchdog
        state: latest
... 

