---
- name: Fail2ban
  hosts: docker
  vars_files:
    - 'vars/vault.yaml'
    - 'vars/fail2ban.yaml'
  tasks:
    - name: install fail2ban
      package:
        name: "{{ item }}"
        state: present
      loop:
        - fail2ban
        - curl
        - iptables
    - name: install notification sender.
      ansible.builtin.template: 
        src: files/fail2ban/ntfy-fail2ban.sh
        dest: /usr/local/bin/
        mode: 0755
        owner: root
        group: root
      notify:
        - restart fail2ban
       
    - name : install custome filters
      ansible.builtin.template:
        src: files/fail2ban/{{ item }}
        dest: /etc/fail2ban/{{ item }}
        owner: root
        group: root
        mode: 0644
      loop: 
        - action.d/myactions.conf
        - filter.d/seafile.conf
        - filter.d/vaultwarden.conf
        - jail.d/defaults-debian.local
        - jail.d/seafile.local
        - jail.d/vaultwarden.local
      notify:
        - restart fail2ban

    - name: configure iptables chain
      lineinfile:
        path: /etc/fail2ban/action.d/iptables-common.conf
        regexp: "^chain = INPUT"
        line: chain = DOCKER-USER
        backup: yes
      notify:
        - restart fail2ban
 
  handlers:
    - name: restart fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
