---
- name: install and configure inadyn
  hosts: server
  vars_files:
    - 'vars/vault.yaml'
    - 'vars/inadyn.yaml'
  tasks:
    - name: Install inadyn
      package:
        name: inadyn
        state: present
    - name: Copy the inadyn.conf template file
      ansible.builtin.template:
        src: files/inadyn.conf.j2
        dest: /etc/inadyn.conf
        mode: 0640
        owner: root
        group: debian-inadyn
      notify:
        - restart inadyn
    - name: enable inadyn to start
      lineinfile:
        path: /etc/default/inadyn
        regexp: "^RUN_DAEMON=\"no\""
        line: "RUN_DAEMON=\"yes\""
        backup: yes
      notify:
        - restart inadyn

  handlers:
    - name: restart inadyn
      service:
        name: inadyn
        state: restarted
