---

- name: copy replicate script to laptops on server
  hosts: server:test
  vars_files: 
    - 'vars/krb5-laptops.conf'
  tasks:
    - name: copy script krb5-rep.sh
      ansible.builtin.template:
        src: files/krb5-pam/krb5-rep.sh.j2
        dest: /etc/cron.daily/krb5-rep.sh
        owner: root
        group: root
        mode: 0755

- name: enable krb5 client
  hosts: all:!laptops
  vars_files:
    - 'vars/krb5-default.conf'
  tasks:
    - name: customice krb5.conf
      ansible.builtin.template:
        src: files/krb5-pam/krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
    - name:       
      package:
        name: "{{ item }}"
        state: present
      loop:
        - libpam-krb5
        - krb5-user
    - name: configure sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^(#){{ item.key }}"
        line:  "{{ item.key }} {{ item.value }}"
        state: present
        backup: yes
      loop:
        - { key: "GSSAPIAuthentication", value: "yes" }
        - { key: "GSSAPICleanupCredentials", value: "yes" }
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

