---

- hosts: laptops
  vars:
    - krb5_def: laptops
- hosts: all:!laptops
  vars:
    - krb5_def: default

- name: enable krb5 client
  hosts: all
  vars_files:
    - 'vars/krb5-{{ krb5_def }}.conf'
  tasks:
    - name: customice krb5.conf
      ansible.builtin.template:
        src: files/krb5-pam/krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644
    - name:       
      package:
        name: libpam-krb5
        state: present

