- hosts: lamp
  vars_files:
    - vars/lamp.yaml
    - vars/vault.yaml
    
  roles: 
    - moodle
    #- apache
      #- mariadb
  tasks:
    - name: Checkout moodle software
      ansible.builtin.git:
        repo: 'git://git.moodle.org/moodle.git'
        dest: /var/www/moodle.emeteo.duckdns.org/moodle
        version: MOODLE_400_STABLE
        update: no

    - name: Permissions to moodle dir
      ansible.builtin.file:
        path: /var/www/moodle.emeteo.duckdns.org/moodle
        owner: root
        group: root
        mode: '0755'
    - name: Create user for MariaDB / Moodle
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "moodleuser"
        password: "{{ mysql_moodle_password }}"
        state: present
        priv: "moodle.*:SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER"
    #Pendiente, 
    #poner variable max_inputs_vars >5000
    # Instalar el crontab al usuario www-data para el cron del moodle



