---
- name: install and configure NTP
  hosts: all:!pega
  vars_files:
    - 'vars/ntp.yaml'
  tasks:
    - name: Install NTP
      package:
        name: ntp
        state: present
    - name: Copy the ntp.conf template file
      ansible.builtin.template:
        src: files/ntp/ntp.conf.j2
        dest: /etc/ntp.conf
        mode: 0644
        owner: root
        group: root
      notify:
        - restart ntp
  handlers:
    - name: restart ntp
      service:
        name: ntp
        state: restarted
