---
- name: user ansible in all managed
  hosts: desktops infra arm lxc
  tasks:
    - name: user ansible
      ansible.builtin.user:
        name: ansible
        comment: Ansible
        group: ansible
        shell: /bin/bash
        non_unique: true
        uid: 1007
    - name: adding group ansible (1008)
      ansible.builtin.group:
        name: ansible
        gid: 1008
        state: present
        non_unique: true

- name: usuarios comunes
  hosts: all
  tasks:  
    - name: adding emeteo(1000) to adm group and sudo
      ansible.builtin.user:
        name: emeteo
        comment: Mario Teijeiro
        groups: sudo,adm
        uid: 1000
        shell: /bin/bash
        append: yes
- name: quitar usuarios de desktops en servicios
  tags: clean
  hosts: all:!desktops
  tasks:
    - name: delete some users from arm
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - xiana
        - aroa

- name: must be groups  
  hosts: all
  tasks:
    - name: media
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
        non_unique: true
      loop:
        - { name: 'emeteo', gid: 1000 }
        - { name: 'ansible', gid: 1008 }

- name: must be groups  desktops
  hosts: desktops:server:docker
  tasks:
    - name: media
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
        non_unique: true
      loop:
        - { name: 'emeteo', gid: 1000 }
        - { name: 'aroa', gid: 1001 }
        - { name: 'media', gid: 1004 }
        - { name: 'martina', gid: 1006 }
        - { name: 'xiana', gid: 1007 }
        - { name: 'ansible', gid: 1008 }


- name: must be users laptops
  hosts: laptops
  tasks:
    - name: user martina 
      ansible.builtin.user:
        name: martina
        comment: Martina Ramilo Pereira
        group: martina
        groups: media
        uid: 1006
        append: yes
        shell: /bin/bash
        non_unique: true
    - name: user aroa
      ansible.builtin.user:
        name: aroa
        comment: Aroa Teijeiro Ramilo
        group: aroa
        groups: media
        uid: 1002
        append: yes
        shell: /bin/bash
        non_unique: true
    - name: user xiana
      ansible.builtin.user:
        name: xiana
        comment: Xiana Teijeiro Ramilo
        group: xiana
        groups: media
        uid: 1001
        append: yes
        shell: /bin/bash
        non_unique: true


...
