---
- hosts: soundserver,pega
  become: yes
  tasks:
    - name: add zabbix userparameter for fail2ban
      tags:
        - userparameter
      copy:
        src: files/zabbix/fail2ban.conf
        dest: /etc/zabbix/zabbix_agentd.d/fail2ban.conf

    - name: add zabbix user to sudo fail2ban
      tags:
        - userparameter
      copy:
        content: | 
          zabbix ALL=NOPASSWD:    /usr/bin/fail2ban-client status
          zabbix ALL=NOPASSWD:    /usr/bin/fail2ban-client status *
        dest: /etc/sudoers.d/zabbix_f2b
        mode: 0440

- hosts: rpi
  become: yes
  tasks:
    - name: add zabbix userparameter for rpi
      tags:
        - userparameter
      copy:
        src: files/zabbix/rpi/raspberrypi.sh
        dest: /usr/local/bin
        mode: 0755

    - name: add zabbix userparameter for rpi
      tags:
        - userparameter
      copy:
        src: files/zabbix/rpi/rpi.conf
        dest: /etc/zabbix/zabbix_agentd.d/rpi.conf

    - name: add zabbix user to sudo raspberry
      tags:
        - userparameter
      copy:
        content: | 
          zabbix ALL=NOPASSWD:    /usr/local/bin/raspberrypi.sh *
        dest: /etc/sudoers.d/zabbix_rpi
        mode: 0440

    - name: restart zabbix-agent
      tags:
        - userparameter
      service:
        name: zabbix-agent
        state: restarted
    
- hosts: all:!zabbix:!docker
  vars_files:
    - 'vars/zabbix.yaml'
  tasks:
    - name: install gpg
      package:
        name: gpg
        state: present
    - name: install zabbix gpg repository
      ansible.builtin.apt_key:
        id: FBABD5FB20255ECAB22EE194D13D58E479EA5ED4
        url: https://repo.zabbix.com/zabbix-official-repo.key
        keyring: /etc/apt/trusted.gpg.d/zabbix.gpg
    - name: install repository of zabbix
      ansible.builtin.apt_repository:
        repo: "deb https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian {{ ansible_distribution_release }} main"
        state: present
      notify:
        - apt-get update
        - apt-get install
    - name: Install zabbix-agent
      package: 
        name:  zabbix-agent
        state: present

    - name: copy config agent 
      ansible.builtin.template:
        src: files/zabbix/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
      notify:
        - restart zabbix-agent

  handlers: 
    - name: apt-get update
      package:
        update_cache: true
    - name: apt-get install
      package:
        name: zabbix-agent
        state: latest
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
 


    


